name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Tools
        uses: asdf-vm/actions/install@v3
        with:
          # https://github.com/asdf-vm/actions/issues/587
          asdf_branch: v0.15.0

      - name: Before Install
        run: |
          mkdir -p shogi/boards
          touch shogi/boards/temp.sqlite3

      - name: Install JavaScript dependencies
        run: npm ci
